service: flowing-coin-slack-command
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: eu-central-1
  environment:
    COINS_TABLE: "flw-coins-${opt:stage, 'dev'}-1-2022"
    SLACK_TOKEN: "IC4NXN8MzB2jWOS1GITCSaNR"
  httpApi:
    cors: true

functions:
  coin:
    handler: handler.v1.send
    events:
      - httpApi:
          path: /slack
          method: post
  list:
    handler: handler.v1.tickets
    events:
      - httpApi:
          path: /tickets
          method: get

resources:
  Resources:
    CoinsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
          -
            AttributeName: "timestamp"
            AttributeType: "N"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
          -
            AttributeName: "timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.COINS_TABLE}